### ISSUE TITLE
try registering to general directly

### ISSUE THREAD

**Issue by tpapp** [tpapp/ContinuousTimeMarkov.jl#4]
cf https://discourse.julialang.org/t/switching-package-registration-systems-on-monday/22677

@JuliaRegistrator `register()`

**Comment by nkottary** [comment]
You need to quote the register() part, like this: `register()`

**Comment by tpapp** [comment]
@nkottary: I edited the issue, is that enough, or should I close and open a new one?

**Comment by fredrikekre** [comment]
I think edits are not listened for. Try adding a new comment (no idea if that works or if it has to be in the original comment, but I'm curious:))

**Comment by tpapp** [comment]
@JuliaRegistrator `register()`

**Comment by tpapp** [comment]
@fredrikekre : tried this, if you have access to the logs please let me know if it is doing anything, or should I just open that other issue.

**Comment by fredrikekre** [comment]
I don't. But feel free to try with a new issue!

**Comment by tpapp** [comment]
Closing in favor of #5.

**Comment by nkottary** [comment]
Registrator listens to comments also but not edits to the issue content. I think the problem here is that RegistratorTest app has not been installed on this repo.

**Comment by nkottary** [comment]
But if you close and reopen an issue with the edited content, then yes Registrator will be triggered for that.

**Comment by tpapp** [comment]
@nkottary: thanks for all your help, it finally worked. I wrote up some suggestions in https://github.com/JuliaComputing/Registrator.jl/issues/46.
