### ISSUE TITLE
new registration framework take 2

### ISSUE THREAD

**Issue by tpapp** [tpapp/ContinuousTimeMarkov.jl#5]
@JuliaRegistrator `register()`

**Comment by nkottary** [comment]
Have you installed the RegistratorTest app on this repo? I don't see requests coming from this repo in the logs.

You can do so here: https://github.com/apps/registratortest/installations/new

**Comment by tpapp** [comment]
Thanks, it was not clear I had to do that. Closing in favor of #6.
